services:
  - name: mi-bakend
    type: web
    runtime: node
    repo: https://github.com/valdez1245/mi-bakend
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

      - key: DATABASE_URL
        value: postgres://user:password@host:port/dbname
      - key: SECRET_KEY
        value: tu_secreto_aqui
